### ISSUE TITLE
链接mongo使用wheretime查询的时候，报错缺少getFieldType方法

### ISSUE THREAD

**Issue by pig1989811** [top-think/think-orm#111]
报错信息：method not exist:think\db\Mongo->getFieldType
跟踪到builder/Mongo.php的333行$type = $query->getFieldType($key);方法中，getFieldType并不在传入的connector/Mongo.php中。也没找到其他地方存在这个方法。看看是不是缺了

**Comment by liu21st** [comment]
你应该没有更新到最新版 或者用开发版测试下

**Comment by pig1989811** [comment]
我看了2.0.28的版本，是缺少这个方法
