### ISSUE TITLE
因为数据不完整，触发MorphTo.php里eagerlyResultSet报错的建议

### ISSUE THREAD

**Issue by moufer** [top-think/think-orm#120]
因为使用模型的多态关联，有些数据在运营时，进行了删除，这个时候使用MorphTo.php里的eagerlyResultSet会因为找不到对应数据而报错
`throw new Exception('relation data not exists :' . $this->model);`
因为报错，会导致页面无法执行，能否在这里改进下，加一个选项，允许不报错？
因为一些不很重要的数据，有时候允许冗余，只要前端可以判断数据是否存在即可

**Comment by liu21st** [comment]
已经改进和eagerlyResult方法处理一样 不存在则为null
