### ISSUE TITLE
建议增加模型转换类型“string”

### ISSUE THREAD

**Issue by season886** [top-think/think-orm#134]
由于对方数据库设计的是19位数字，输出到前端每次都需要转换，不然超出了js最大支持长度，恰恰看到手册有类型转换，增加了
` protected $type = [
        'id'         => 'string',
        'pid'  => 'string'
    ];
`
最后跑源码发现并没有处理string类型，只需要输出为string，发送到数据库执行语句还是要按照其类型跑，或者schema类型

**Comment by big-dream** [comment]
建议使用获取器解决这个问题

**Comment by season886** [comment]
@big-dream 我定义了获取器，但是column与value好像不执行获取器，只有find，select才会执行，能统一下么？
