### ISSUE TITLE
建议ORM支持一对一、一对多动态模型关联

### ISSUE THREAD

**Issue by mydzoo** [top-think/think-orm#140]
Thread主表、ThreadInfo、ThreadTweet等等是横向拆分表，通过Thread表的module字段来动态识别关联哪张表。
```
//关联模型
    public function entity()
    {
        $entityClass = ThreadClassType::getClass($this->module);
        return $this->hasOne($entityClass, 'thread_id', 'id');
    }
```

```
class ThreadClassType
{
    public static $classes = [
        'info'    => ThreadInfo::class,
        'tweet'   => ThreadTweet::class,
        'video'   => ThreadVideo::class,
        'article' => ThreadArticle::class
    ];
    public static function getClass($type)
    {
        if (array_key_exists($type, static::$classes)) {
            return static::$classes[$type];
        }
        throw new HttpException(404, "Object type \"{$type}\" was not found.");
    }
}
```
通过Thread:where(xxx)->with('entity')无法正常加载出动态关联模型信息(只识别第一个)，通过append形式可以得到正常结果，但是`关联预载入`功能没有了。

So，建议ORM可以支持一对一、一对多动态模型关联，总之就是能够解决这个场景的应用，并且`关联预载入`好使那就完美了。

**Comment by liu21st** [comment]
不就是多态一对一 一对多么？

**Comment by mydzoo** [comment]
按照上面的场景：
多态一对一`ThreadInfo,ThreadTweet,ThreadVideo`这些是主表，具有自增ID，而`Thread`是多态表且多态表必须包含一个`xxx_type`和`xxx_id`的字段。

但是目前mysql设计的表情况是：`Thread`表中仅仅包含一个`module`字段来区分它的`横向拆分表`是哪张，比如是`info`就对应`ThreadInfo`表、`article`就对应`ThreadArticle`表，其他一样。

而`横向拆分表`仅仅包含`thread_id`字段和其他不同于其他`横向拆分表`的字段。

比如`新浪微博`可以发布`短视频`，`短微博`，`长文章`，`链接`等等，站在`Thread`的角度可以很轻松的把这些不同类型的帖子`聚合`显示到一起。

和`多态一对一 `最大的区别就是站立的角度不同，前者站在`Thread`表的角度，后者站在`横向拆分表`的角度。

**Comment by liu21st** [comment]
我不认为有啥区别

**Comment by mydzoo** [comment]
多态一对一必须包含一个`xxx_type`和`xxx_id`的字段，那么按现在的情况是数据表设计不合理，必须添加字段吗？无论是`横向拆分表`还是`Thread`表都需要各自自增？

**Comment by liu21st** [comment]
字段名是可以自定义的 但肯定是需要两个字段才能界定数据的 你的设计是只有主表有主键 拆分表没有主键是吧？那你两个表之间通过什么字段关联，最好是给出你的数据结构设计参考

**Comment by mydzoo** [comment]
是的，只有主表有主键，拆分表没有主键。下面是精简的mysql
```
CREATE TABLE `thread` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `module` varchar(50) NOT NULL DEFAULT 'tweet' COMMENT '模型',
  `forum_id` int(11) NOT NULL DEFAULT '0' COMMENT '社圈ID',
  `user_id` int(11) NOT NULL DEFAULT '0' COMMENT '作者ID',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='主题基础表';
```
```
CREATE TABLE `thread_article` (
  `thread_id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL COMMENT '标题',
  `content` mediumtext NOT NULL,
  PRIMARY KEY (`thread_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='文章模型';
```
```
CREATE TABLE `thread_video` (
  `thread_id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL COMMENT '视频标题',
  `url` varchar(255) NOT NULL COMMENT '视频链接',
  PRIMARY KEY (`thread_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='短视频模型';
```
关联的方法在最上面提问问题贴出过代码，查询某一类型，如文章就where(['module' => 'article'])

**Comment by yunwuxin** [comment]
这个不就是一对一的多态么

xxx_type和xxx_id 这两个字段是可以自定义的

**Comment by mydzoo** [comment]
是指的`xxx_id`就是thread表的`id`吗？恍然大悟
