### ISSUE TITLE
Collection中自动时间戳字段查询的问题

### ISSUE THREAD

**Issue by liuqiandev** [top-think/think-orm#155]
针对Collection实例中的自动时间戳字段使用where查询时,自动时间戳字段会自动转换为数据库配置文件中的时间格式,导致查询结果与实际不符.

```
$userList = User::field(['id','update_time'])->select();
$userList->where('update_time','>',1592299250)->count();
```
如果数据库配置文件中设置`datetime_format`不为`false`会导致结果不正确

**Comment by liu21st** [comment]
如果你开启了自动转换的话 那么数据集的查询也要换成日期方式的 否则你就要在查询之前限制条件了

**Comment by liuqiandev** [comment]
行吧,虽然知道为什么会这样,但感觉怪怪的
