### ISSUE TITLE
断线重连机制不完整

### ISSUE THREAD

**Issue by zyuelei** [top-think/think-orm#156]
![image](https://user-images.githubusercontent.com/13957066/85965547-9832a680-b9ef-11ea-9b12-84e67f8e869d.png)
命令行长连接，配置中开启了break_reconnect
然后我的sql是插入数据库一些数据，在开启事务的时候报了has gone away的错误是不会进入断线重连的判断中的，会直接向最外层抛出异常。

**Comment by liu21st** [comment]
已经改进
