### ISSUE TITLE
数据库查询缓存cache偶发性报错

### ISSUE THREAD

**Issue by zyuelei** [top-think/think-orm#159]
![image](https://user-images.githubusercontent.com/13957066/86217357-f3ac9200-bbb1-11ea-91a0-02ac7c46823a.png)

当缓存在redis中，在使用数据库查询缓存的cache方法时，$this->cache->has($name)是有的，但是接下来在redis中数据缓存过期了，$this->cache->get($name)返回了null，就报错了：
![image](https://user-images.githubusercontent.com/13957066/86217275-d5469680-bbb1-11ea-9d6a-8f677de92715.png)

同理能看见其他很多地方都是这个逻辑可能导致报错。
好在这个错误出现概率极低。。。

**Comment by liu21st** [comment]
你这是用的老版本吧 新版改进过这个问题的

**Comment by zyuelei** [comment]
确实，新版有改，谢谢
