### ISSUE TITLE
Db Facade类 Phpstorm最新版本没有代码提示

### ISSUE THREAD

**Issue by midsmr** [top-think/think-orm#160]
如图:
![批注 2020-07-02 101508](https://user-images.githubusercontent.com/61633355/86308919-f1e3dc80-bc4c-11ea-9d08-d422f2ff67c7.png)
好像是因为注释原因
希望官方能够在下个版本搞一搞
（哈哈哈）

**Comment by dkoin** [comment]
希望尽快完善一下，从5.1同步过来，应该费不了多少时间
