### ISSUE TITLE
更新到2.0.33后，多对多关联统计报错

### ISSUE THREAD

**Issue by big-dream** [top-think/think-orm#161]
发现用了多对多关联关联统计的地方均报错`SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'pivot'`

主要原因是关联方法里面使用了`where`方法，触发了`\think\model\Relation::__call()`。`\think\model\relation\BelongsToMany::getRelationCountQuery()`和`\think\model\Relation::__call()`执行了`\think\model\relation\BelongsToMany::belongsToManyQuery()`方法，导致`join`规则重复

使用方法依照TP6手册上的测试也是不行的。

详细错误跟踪流程：https://blog.ll00.cn/archives/179.html

**Comment by liu21st** [comment]
最新的开发版测试下

**Comment by big-dream** [comment]
更新到最新开发版之后，不会报错，但是数据不对。查看SQL语句，发现其中一个条件异常（`pivot`.`label_id` IS NULL）。
```
SELECT *,(SELECT COUNT(*) AS think_count FROM `task` INNER JOIN `task_label_pivot` `pivot` ON `pivot`.`task_id`=`task`.`id` WHERE  `pivot`.`label_id` IS NULL  AND `status` > 0) AS `task_count` FROM `task_label` ORDER BY `create_time` DESC LIMIT 0,10
```
composer执行结果
```
composer require topthink/think-orm:2.0.x-dev
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Removing topthink/think-orm (v2.0.32)
  - Installing topthink/think-orm (2.0.x-dev c479283): Cloning c479283e45 from cache
Writing lock file
Generating autoload files
> @php think service:discover
Succeed!
> @php think vendor:publish
File \config\trace.php exist!
Succeed!
```

**Comment by big-dream** [comment]
尝试了修改，修改后测试这块功能正常，已提交PR，不知道是不是最优的解决方法^-^
