### ISSUE TITLE
when 使用的小问题

### ISSUE THREAD

**Issue by yzh52521** [top-think/think-orm#164]
->when($condition, function ($query) use ($wx, $tel) {
                $query->where('cp_info', '=', $wx)->whereOr('cp_info', '=', $tel);
            });
AND `cp_month` = '06' AND `cp_day` = '14' AND `cp_info` = 11 OR `cp_info` = 22
生成的语句 没有用括号括起来

**Comment by liu21st** [comment]
已经改进了 可以用最新开发版测试下
