### ISSUE TITLE
Db join一个bug

### ISSUE THREAD

**Issue by 4352570** [top-think/think-orm#171]
更正一下，和join无关，是find遇到的情况
Db::table('order')
                    ->field('sum(order_price),count(DISTINCT shop_id),count(DISTINCT mobile)')
                    ->where('shop_id', '<>', 3)
                    ->find();

如以上查询 如果没有where 条件的话，没有任何结果，也没有getlastsql,
加任一where就能正常使用

**Comment by liu21st** [comment]
设计如此 不加任何条件的话 是不会返回数据的
