### ISSUE TITLE
error while sending stmt_close

### ISSUE THREAD

**Issue by flydo228** [top-think/think-orm#18]
![selection_007](https://user-images.githubusercontent.com/24283064/35093959-d2951d0c-fc7e-11e7-9aef-e097e7eb22ad.png)

报错了。我看了下ThinkPHP，有人也说有这个问题。

http://www.thinkphp.cn/topic/48219.html

**Comment by liu21st** [comment]
改进了下，记得开启断线重连的配置参数

**Comment by flydo228** [comment]
能不能也把```composer```的更新一下？我是用```composer install```的。。。

**Comment by liu21st** [comment]
等下一次更新吧 总不能改个东西就发一个版本吧~

**Comment by flydo228** [comment]
...好吧。那我直接```git clone```源替换```composer```的文件吧。

**Comment by liu21st** [comment]
我更想了一个版本 你可以重新测试下
