### ISSUE TITLE
php 7+ CLI下 报两处错误

### ISSUE THREAD

**Issue by Zsoner** [top-think/think-orm#19]
![image](https://user-images.githubusercontent.com/11805413/35144696-3fa82a8a-fd40-11e7-8584-b60bb4441f04.png)

![image](https://user-images.githubusercontent.com/11805413/35144742-6d090404-fd40-11e7-8476-17b54af0809c.png)
public function toCollection($collection,)
缺少第二个参数
public function toCollection($collection,$resultSetType)
上面这个错误是昨晚最新包1.2的

![image](https://user-images.githubusercontent.com/11805413/35144729-613a6c58-fd40-11e7-8249-370b96a218d7.png)
![image](https://user-images.githubusercontent.com/11805413/35145076-77343808-fd41-11e7-906e-4f8ce7c0ef45.png)

这个一直有，不知是环境问题还是用法错误，我的理解是
`use think\Collection;
use think\db\connector\Mongo as Connection;`
这里重复了，导致下面的__construct 中的Connection错误，反正我改成
`use think\db\connector\Mongo as mConnection;`

`/**
     * 架构函数
     * @access public
     */
    public function __construct(mConnection $connection = null)
    {
        if (is_null($connection)) {
            $this->connection = mConnection::instance();
        } else {
            $this->connection = $connection;
        }

        $this->prefix = $this->connection->getConfig('prefix');
    }`
后下面正常使用

**Comment by liu21st** [comment]
感谢反馈 已经修正

**Comment by Zsoner** [comment]
第二个问题依然报错，可能原因是：在常驻的应用中 Query中有申明 use think\Collection;影响所导致，所以最好另起别名可能会好一些。

**Comment by liu21st** [comment]
改进了
