### ISSUE TITLE
疑似SQL构造BUG

### ISSUE THREAD

**Issue by wxkxklmyt** [top-think/think-orm#194]
版本：6.0.4，其它版本未测试
`ArticleModel::where('status','1')  -> whereFindInSet('parent_ids', 1, 'or')->select();`
期望生成SQL
`SELECT * FROM wx_article WHERE status=1 OR FIND_IN_SET(1, parent_ids)`
实际生成SQL
`SELECT * FROM wx_article WHERE status=1 AND FIND_IN_SET(1, parent_ids)`
相当于whereFindInSet方法的第3个参数默认为AND，即使设置成OR也是没有什么用

**Comment by liu21st** [comment]
测试没有发现问题 你用的是什么数据库？

**Comment by wxkxklmyt** [comment]
> 测试没有发现问题 你用的是什么数据库？

mysql5.7
whereFindInSet是在闭包中使用的

**Comment by wxkxklmyt** [comment]
又正常了，再出现再说吧
