### ISSUE TITLE
mongodb连接缺少database导致报Authentication failed错误

### ISSUE THREAD

**Issue by kingfer30** [top-think/think-orm#195]
这个问题很久了，啥时候修复一下？

https://github.com/top-think/think-orm/blob/2.0/src/db/connector/Mongo.php#L158

![image](https://user-images.githubusercontent.com/34082198/96092504-8c66e380-0efd-11eb-8be5-11b6599af167.png)

**Comment by liu21st** [comment]
用 authSource 参数配置鉴权
