### ISSUE TITLE
数组条件查询，有like关键字的时候报错如where express error:%thinkphp"

### ISSUE THREAD

**Issue by zithan** [top-think/think-orm#20]
Db::table('think_user')
    ->where([
        'title' =>  ['like','%thinkphp']
    ])
    ->select();

<br />
<b>Notice</b>:  Undefined offset: 1 in
<b>/var/www/logistics/admin/vendor/topthink/think-orm/src/db/Builder.php</b> on line
<b>389</b>
<br />
string(26) "where express error:%thinkphp"

**Comment by liu21st** [comment]
不支持这种数组查询了的 参考5.1的开发手册可以

**Comment by DkHHW** [comment]
Db::table('think_user')
->where([
'title' => ['title','like','%thinkphp']
])
->select();
