### ISSUE TITLE
PHP8中需要修复2处代码

### ISSUE THREAD

**Issue by coolxitech** [top-think/think-orm#204]
PDOConnection.php 1243行
会报substr_replace函数传参类型错误
`substr_replace($sql, $value, strpos($sql, '?'), 1) :`
`substr_replace($sql, $value, strpos($sql, ':' . $key), strlen(':' . $key));`
改成
`substr_replace($sql, (string)$value, strpos($sql, '?'), 1) :`
`substr_replace($sql, (string)$value, strpos($sql, ':' . $key), strlen(':' . $key));`
遇到类似情况可以手动修复

**Comment by liu21st** [comment]
这个早就修复过的开发版
