### ISSUE TITLE
where In 查询空数组时的改进

### ISSUE THREAD

**Issue by NHZEX** [top-think/think-orm#225]
```Db::table('test_user')->whereIn('type', [])->column('*')```转换的实际sql语句是```SELECT * FROM `test_user` WHERE  `type` IN ('')```

更改为```WHERE 0 = 1```OR```WHERE FALSE```应该更合适，使数据库不会发生实际的查询，EXPLAIN 结果 `Impossible WHERE`

相关讨论 
https://github.com/typeorm/typeorm/issues/2195#issuecomment-706658209
https://github.com/typeorm/typeorm/pull/6887#issuecomment-706668187
https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Query/Grammars/Grammar.php#L265-L272

**Comment by liu21st** [comment]
一般场景下 不太会空 所以也没有特别处理空的情况
