### ISSUE TITLE
可以添加个开关来禁止数据库的某些字段禁止隐式转换吗？

### ISSUE THREAD

**Issue by resnou** [top-think/think-orm#228]
系统一路从thinkphp5升级过来的，现在数据库字段用string存储的数字。

目前进行数据库大于和小于查询，thinkphp都会把传入的查询数字转换为字符串，

非常希望可以添加个禁止某些字段进行隐式转换，或者指定某些字段为数字的功能。

https://github.com/top-think/framework/issues/2462

**Comment by liu21st** [comment]
Db类提供了setFieldType方法的 模型的话可以设置schema属性

**Comment by resnou** [comment]
> Db类提供了setFieldType方法的 模型的话可以设置schema属性

谢谢回复！之前在官方手册中没有发现有这个方法。

**Comment by liu21st** [comment]
这个方法一般不太建用 所以没有写出来 但模型的schema功能正是调用了这个方法的

**Comment by resnou** [comment]
提个建议，在数据库的手册那块告诉一下用户，thinkphp会自动获取数据库的字段，并且自动修正用户传入的查询数据的类型，我印象中thinkphp5好像是不会修改用户传入的查询数据类型，近期发现系统查询的数据不正确，然后查看LOG文件又没发现异常，折腾了半天才发现thinkphp有隐式转换这个功能。
