### ISSUE TITLE
v2.0.37 版本导致 swoole v3.1.1出现问题 请修正一下

### ISSUE THREAD

**Issue by 147317963** [top-think/think-orm#232]
v2.0.37 版本导致 swoole v3.1.1出现问题 请修正一下

**Comment by etjson** [comment]
是的，我也是，全报错了，报错内容：
Declaration of think\swoole\pool\proxy\Connection::column(think\db\BaseQuery $query, string $column, string $key = ''): array must be compatible with think\db\ConnectionInterface::column(think\db\BaseQuery $query, $column, string $key = '')

**Comment by etjson** [comment]
think-swoole作者已经提交修复[https://github.com/top-think/think-swoole/commit/eb7f78b7eb53dde79257f4254fe61f9514f3c7d8](https://github.com/top-think/think-swoole/commit/eb7f78b7eb53dde79257f4254fe61f9514f3c7d8)等待作者发布更新即可。

**Comment by 147317963** [comment]
我的报错是这个    但不知道为什么报错在终端命令里面   你是怎么报错在网页的。。。我直接网页空白 我查看终端才知道这个错误

**Comment by bellpk** [comment]
issue怎么关了，时至两天前的2.0.39依然没有修复
