### ISSUE TITLE
2.0.37 isAutoWriteTimestamp方法报错

### ISSUE THREAD

**Issue by ChinaMoli** [top-think/think-orm#238]
$user = User::find(1);
$user->read +=1;
$user->isAutoWriteTimestamp(false)->save();
提示：SQLSTATE[01000]: Warning: 1265 Data truncated for column 'update_time' at row 1

版本回滚到2.0.34就正常了

**Comment by liu21st** [comment]
你用最新版本测试下看看

**Comment by ChinaMoli** [comment]
解决了
