### ISSUE TITLE
请教一下这个报错怎么处理。

### ISSUE THREAD

**Issue by etjson** [top-think/think-orm#240]
`[2021-02-23T10:49:52+08:00][error] [1]Uncaught think\db\exception\PDOException: SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute. in /www/wwwroot/xxx.com/vendor/topthink/think-orm/src/db/PDOConnection.php:768
Stack trace:
#0 /www/wwwroot/xxx.com/vendor/topthink/think-orm/src/db/connector/Mysql.php(66): think\db\PDOConnection->getPDOStatement()
#1 /www/wwwroot/xxx.com/vendor/topthink/think-orm/src/db/PDOConnection.php(396): think\db\connector\Mysql->getFields()
#2 /www/wwwroot/xxx.com/vendor/topthink/think-orm/src/db/PDOConnection.php(336): think\db\PDOConnection->getTableFieldsInfo()
#3 /www/wwwroot/xxx.com/vendor/topthink/think-orm/src/db/PDOConnection.php(383): think\db\PDOConnection->getSchemaInfo()
#4 /www/wwwroot/xxx.com/vendor/to`

请教一下这个报错怎么处理？

**Comment by etjson** [comment]
topthink/framework                   v6.0.7  The ThinkPHP Framework.
topthink/think-orm                    v2.0.38 think orm
topthink/think-swoole               v3.1.2  Swoole extend for thinkphp

**Comment by chengweijian** [comment]
@etjson 请问解决了吗？

**Comment by chengweijian** [comment]
@etjson  可以尝试update php的版本7.2以上
