### ISSUE TITLE
v2.0.38 版本开始 Model 的 事件触发 的数据都是修改前的数据

### ISSUE THREAD

**Issue by 502647092** [top-think/think-orm#241]
v2.0.38 版本开始 Model 的 事件触发 的数据都是修改前的数据
例如 
```php
$order = Orders::getById(1) ;//['id'=>1, 'status'=>0];
$order->status = 1;
$order->save();
```
触发的 `onAfterWrite` 事件中
```php
class Orders extends Model
{
    public static function onAfterWrite($order)
    {
        // 此处的 status是查询到的0  而不是修改后的1
        if ($order->status == 1) {
          //xxxxxxx
        }
    }
}
```

**Comment by 502647092** [comment]
@liu21st 问题比较严重 影响项目运行 逻辑都乱了

**Comment by liu21st** [comment]
我测试没发现你说的问题哦

**Comment by 502647092** [comment]
> 我测试没发现你说的问题哦

我项目上出现的问题 情况紧急 我直接降级到 v2.0.37 没问题

我等下重新建一个干净的项目测试一下

**Comment by 502647092** [comment]
@liu21st 测试过了 的确有问题
我新建的项目测试的
测试代码
控制器
```php
<?php

namespace app\controller;

use app\BaseController;
use app\model\Tests;

class Index extends BaseController
{
    public function test()
    {
        $test = Tests::getById(1);
        echo 'Read From Database: '.json_encode($test).'<br>';
        $test->status = 1;
        $test->save();

        return '';
    }
}
```
模型类
```php
<?php

namespace app\model;

use think\Model;

class Tests extends Model
{
    public static function onBeforeUpdate($test)
    {
        echo 'onBeforeUpdate'.\json_encode($test).'<br>';
    }

    public static function onAfterUpdate($test)
    {
        echo 'onAfterUpdate'.\json_encode($test).'<br>';
    }

    public static function onBeforeWrite($test)
    {
        echo 'onBeforeWrite'.\json_encode($test).'<br>';
    }

    public static function onAfterWrite($test)
    {
        echo 'onAfterWrite'.\json_encode($test).'<br>';
    }
}
```
输出结果
![image](https://user-images.githubusercontent.com/10203793/109273672-74a94f80-784d-11eb-9ab5-23a25ae80d21.png)

<del>理论上 onAfterXXX 的数据 status 应该是1 而不是0<del>

描述错误 应该是 所有触发的事件 结果 应该都是修改后的 而不是修改前 并不单单是 onAfterXXX

**Comment by 502647092** [comment]
降级之后 恢复数据 重新执行 结果正常
```log
[root@2-5 MiaoWeb6-test]# composer require topthink/think-orm:v2.0.37
./composer.json has been updated
Running composer update topthink/think-orm
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
  - Downgrading topthink/think-orm (v2.0.38 => v2.0.37)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Downgrading topthink/think-orm (v2.0.38 => v2.0.37): Extracting archiveGenerating autoload files
> @php think service:discover
Succeed!
> @php think vendor:publish
File /yumc/app/nfs/theia/PHPWorkSpace/MiaoWeb6-test/config/trace.php exist!
Succeed!
6 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```
执行结果
![image](https://user-images.githubusercontent.com/10203793/109273899-c7830700-784d-11eb-9304-f981138c1ea0.png)

**Comment by 502647092** [comment]
好像应该是 所有触发的事件 数据都不对 而不单单是 onAfterXXX的
理论上触发的结果 都应该是修改之后的数据 而不是修改之前的

**Comment by liu21st** [comment]
用最新开发版测试一下看看

----------

该邮件从移动设备发送




--------------原始邮件--------------
发件人："MiaoWoo "<notifications@github.com&gt;;
发送时间：2021年2月26日(星期五) 下午4:15
收件人："top-think/think-orm" <think-orm@noreply.github.com&gt;;
抄送："ThinkPHP "<liuchen@topthink.net&gt;;"Mention "<mention@noreply.github.com&gt;;
主题：Re: [top-think/think-orm] v2.0.38 版本开始 Model 的 onAfterXXXX 的数据都是修改前的数据 (#241)
-----------------------------------

 

 
降级之后 恢复数据 重新执行 结果正常
 [root@2-5 MiaoWeb6-test]# composer require topthink/think-orm:v2.0.37 ./composer.json has been updated Running composer update topthink/think-orm Loading composer repositories with package information Updating dependencies Lock file operations: 0 installs, 1 update, 0 removals   - Downgrading topthink/think-orm (v2.0.38 =&gt; v2.0.37) Writing lock file Installing dependencies from lock file (including require-dev) Package operations: 0 installs, 1 update, 0 removals   - Downgrading topthink/think-orm (v2.0.38 =&gt; v2.0.37): Extracting archiveGenerating autoload files &gt; @php think service:discover Succeed! &gt; @php think vendor:publish File /yumc/app/nfs/theia/PHPWorkSpace/MiaoWeb6-test/config/trace.php exist! Succeed! 6 packages you are using are looking for funding. Use the `composer fund` command to find out more!  
执行结果

**Comment by 502647092** [comment]
> 用最新开发版测试一下看看

`composer require topthink/think-orm:2.0.x-dev` 切到开发版 测试了 没问题 可以用了
