### ISSUE TITLE
thinkphp6.0.7 模型 each 无法重新赋值

### ISSUE THREAD

**Issue by BlueOfTheSea** [top-think/think-orm#242]
$CompanyDao=$this->DepartmentDao->where($where)->paginate(10)->each(function ($val)use($company){
        $title=$company->where('id',$val['company_id'])->find()['company_nickname'];
        $val['department_name']=$val['department_name']."($title)";
}); //

department_name这个key无法重新赋值

**Comment by BlueOfTheSea** [comment]
composer 2.0.36包是正常的 求作者 更改下此问题

**Comment by liu21st** [comment]
最新开发版修正了的

**Comment by NHZEX** [comment]
> 最新开发版修正了的

能发个修正版本么，直接用dev版本不方便啊
