### ISSUE TITLE
tp-orm 设置缓存 tp-cache 报错

### ISSUE THREAD

**Issue by yuanzhihai** [top-think/think-orm#261]
Db::setCache(Cache::store('file'));
报错
TypeError: Return value of think\db\PDOConnection::pdoQuery() must be of the type array, bool returned in /Users/yuanzhihai/Sites/local/webman/vendor/topthink/think-orm/src/db/PDOConnection.php:694

修改成 

if (null !== $data && false !==$data) {
                return $data;
            }
            就没问题了

**Comment by ijoywan** [comment]
对，这个支持下，最好的方案是不是楼上这么改，而是

```
 $data = $this->cache->get($key,null);
```
