### ISSUE TITLE
字符串查询使用占位符预处理机制绑定参数的时候，拼接sql语句有误

### ISSUE THREAD

**Issue by nanziok** [top-think/think-orm#269]
当使用:绑定的时候，如果sql中出现重复参数，第二个相同参数将不能解析

关键代码
src\db\PDOConnection.php：行：1282
`            
$sql = is_numeric($key) ?
substr_replace($sql, $value, strpos($sql, '?'), 1) :
substr_replace($sql, $value, strpos($sql, ':' . $key), strlen(':' . $key));
`
修改意见：
`
$sql = is_numeric($key) ?
substr_replace($sql, $value, strpos($sql, '?'), 1) :
str_replace(':' . $key, $value, sql);
`

**Comment by liu21st** [comment]
框架目前的处理机制 不会出现重复的参数
