### ISSUE TITLE
独立使用ORM组件，进行分页时，无法自动获取分页，需要手动传参

### ISSUE THREAD

**Issue by yuan-dian** [top-think/think-orm#290]
原因是：在使用框架时有内置的服务注册了PaginatorService服务，单独立使用ORM组件时，由于没有服务注册导致无法获取当前页码
`    public static function currentPageResolver(Closure $resolver)
    {
        static::$currentPageResolver = $resolver;
    }`
这个方法没有被调用

目前需要手动传参`->paginate(['page'=>$page])`才能获取分页

**Comment by augushong** [comment]
不算bug,就是这种特性,应该不会兼容这种情况的,
假设你在workerman或swoole环境,甚至是tcp/text传输数据的环境,就是应该自己手动传参,
否则orm就要做关于$_REQUEST的兼容,并不优雅.
