### ISSUE TITLE
php 8.1 版本运行报错

### ISSUE THREAD

**Issue by AiMuC** [top-think/think-orm#312]
![image](https://user-images.githubusercontent.com/31570354/145385976-050e11b7-0ffd-450e-a157-fcf204e7fd6c.png)

![image](https://user-images.githubusercontent.com/31570354/145386019-51bd5259-60b1-4cd5-a917-ced32708bbf3.png)

**Comment by liu21st** [comment]
兼容问题已经修复

**Comment by AiMuC** [comment]
已经收到了您的来件~

**Comment by Tinywan** [comment]
@liu21st 这个问题是什么时候发布新版本？

**Comment by gaoyayun** [comment]
![image](https://user-images.githubusercontent.com/25237282/154653497-4307da32-7676-44aa-a095-840d8ce0ec84.png)
更新以下版本就好了

**Comment by AiMuC** [comment]
已经收到了您的来件~
