### ISSUE TITLE
新版查询出的模型或集合,赋值数组时,会被转成json字符串

### ISSUE THREAD

**Issue by augushong** [top-think/think-orm#320]
```php
$list = Nav::where('id','<',5)->select();

foreach ($list as &$value) {
    $value->tags = Nav::find(1);
}

dump($list);
```

这段代码,以前`2.0.50`时会打印对象,之后的两个版本会打印json后的对象

- 以前`2.0.50`
![图片](https://user-images.githubusercontent.com/31880431/153532554-82923dc5-a479-4f3c-9b18-f74d7fe8efbe.png)

- 现在 `2.0.50`之后
![图片](https://user-images.githubusercontent.com/31880431/153532613-89947154-3452-41a5-93dc-fca627df555e.png)

**Comment by augushong** [comment]
这个是不小心造成的,还是确定以后就是这样的特性.

**Comment by augushong** [comment]
我觉得不应该这样,如果有人希望一个模型被赋值成json的话,
```
$value->tags = (string)Nav::find(1);
```
显示的要求string即可.

**Comment by liu21st** [comment]
你是说find查询结果变成了json字符串？没有这样的特性吧

**Comment by augushong** [comment]
查询的结果,赋值给一个查询的列表.


```
$list = Nav::where('id','<',5)->select();

foreach ($list as &$value) {
    $value->tags = Nav::find(1);
}
```

像这个代码,打印`$list`,其中元素的tags应该是正常的对象才对,但实际上,就如截图一样,成了json字符串.

**Comment by augushong** [comment]
不只是赋值给列表,
```
 $model_nav = Nav::find(1);

        $model_nav->tags = Nav::find(1);

        dump($model_nav->tags);
```

这样打印的赋值,也是json字符串.

**Comment by liu21st** [comment]
你直接打印 model_nav是什么

**Comment by augushong** [comment]
```
        $model_nav = Nav::find(1);

        $model_nav->tags = Nav::find(1);
        dump($model_nav->tags);

        $model_nav->tags_arr = [
            '工程师',
            '全栈'
        ];
    
        dump($model_nav->tags_arr);


        $obj = new stdClass();
        $obj->tag1 = '工程师';
        $model_nav->tags_obj = $obj;
        dump($model_nav->tags_obj);

        dump($model_nav);
```

像这样一段代码,
打印`tags_arr`,`tags_obj`,都是正常的数组或对象,但是打印`tags`,获取的就是json字符串;

- 截图(数组有点复杂了,只截一部分)
![图片](https://user-images.githubusercontent.com/31880431/153533870-e85d9455-b3d3-4989-84d6-65562c5a510c.png)

**Comment by augushong** [comment]
![图片](https://user-images.githubusercontent.com/31880431/153534007-4a954dab-34ec-43c1-90d5-98b60368f8b4.png)

origin里没有这三次赋值,这是正常的.


get里有这三个赋值,数据如截图

**Comment by wangshikun** [comment]
我也遇到了同样的问题, 就是模型对象在赋值给一个模型数据的时候 的时候,
`
$classB=new model2()//一个数据模型
$list=new model1()//一个数据模型
$list['a']=$classB
halt($list)
`
 对象会自动解释为字符串.  
如果这个时候打印halt($list)发现 $list[`a`]是字符串不是对象 


可能是下面的原因
![image](https://user-images.githubusercontent.com/21035664/154220956-7d94b51e-ebeb-45ea-8870-6ef82ee49d15.png)
![image](https://user-images.githubusercontent.com/21035664/154220984-15758cb8-4576-414b-8240-4d25df5d54ee.png)
我给对象赋值, 会出发获取器,然后就被转化为字符串了

**Comment by mrdznet** [comment]
我也遇到一个问题，使用  ->with(['build', 'floor'])  调用，然后用bind 绑定到父模型上
`
 public function build()
 {
        return $this->hasOne(Building::class, 'id', 'build_id')->field(['id', 'build_name'])->bind(['build_name' => 'build_name',]);
 }
// 更新到新版本后，父对象 查询结果回多一个 build 对象  ，原来只有 build_name 字段

{
    build_name:'xxxxxx',
    build:{
         id:4444,
         build_name:'xxxxxx',
    }
}

`

**Comment by liu21st** [comment]
把模型赋值给其它模型 这种操作不规范也不建议 应该尽量通过关联来操作

**Comment by augushong** [comment]
```
elseif (is_object($value) && method_exists($value, '__toString')) {
      // 对象类型
      $value = $value->__toString();
  }
```
这段代码其实不需要也不应该做这种判断操作,如果要将一个复杂的数据存入数据库,应该专门在模型中定义清楚,像这样:
```
 public function setRefundResultAttr($value)
    {
        return serialize($value);
    }

    public function getRefundResultAttr($value)
    {

        if (empty($value)) {
            return [];
        }
        return unserialize($value);
    }
```

很多时候我们将一个对象(或模型对象)传递给一个模型(或模型数据集),是为了展示方便,不需要存入,甚至也是为了利用虚拟模型的一些特性,如果以后只能提前定义好关联数组或获取器,极不方便做临时的查询或者缓存,毕竟模型的缓存后,在缓存中读取,也会执行获取器的代码.

**Comment by liu21st** [comment]
这段代码是一种通用处理 主要是为了时间对象的写入 另外你如果需要赋值模型的话 可以用setRelation方法 而不是直接给模型赋值

**Comment by augushong** [comment]
我看到最新的提交了,会自动判断是否是模型类.

我还是感觉这种判断不太好,

比如我将一个`SimpleXMLElement`设置到模型中,以便传递这个模型给其他方法继续调用,但是因为这个对象存在`__toString`,就导致模型中存储的就是字符串了,而不是对象.

这种操作,以后就不能随便把一个对象设置到模型上了,我觉得如果需要这样做的话,还是让开发者明确的指出`(string)Object`最好.

**Comment by augushong** [comment]
如果是为了处理时间对象的写入,能不能专门处理时间对象.

很多时候给模型设置数据不是为了写入,即便是写入数据,不存在的字段也会自动过滤掉,基于这种特性,我们可以随意给模型对象设置数据,就是为了方便后续的调用或导出.

如果会自动判断__toString,那就比较麻烦了,这种情况,可能只有将查出来的数据`toArray`才能随便设置对象数据了.

**Comment by liu21st** [comment]
重新调整了下判断逻辑
