### ISSUE TITLE
常驻内存swoole项目爆内存

### ISSUE THREAD

**Issue by shaukei** [top-think/think-orm#363]
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /srv/sync/vendor/topthink/think-orm/src/db/concern/ParamsBind.php on line 52
![image](https://user-images.githubusercontent.com/1581783/178645920-6ab3eef8-192a-41c9-ad4a-5df038ef21de.png)

看样子是bind参数没有释放，临时方法每次查询完后getBind(true)来清空bind

**Comment by shaukei** [comment]
是我用法有问题还是怎样的？没人回应？

**Comment by zoujingli** [comment]
常规 cgi,fpm 框架或组件在常驻内存框架中运行，多多少少会有点问题，就像 ORM 的日志处理也会爆内存，workerman 官方就有指出过。使用常驻内存框架，最好使用推荐的组件，要充分了解其代码实现。

**Comment by shaukei** [comment]
行吧，既然别人（名人）也是爆内存，我爆内存也是正常的！

我换。

**Comment by big-dream** [comment]
https://github.com/top-think/think-orm/commit/2d488afbb9167189eaa65e3d196347f35b232d42
