### ISSUE TITLE
hasWhere无法多次使用

### ISSUE THREAD

**Issue by ajiho** [top-think/think-orm#378]
想根据多个模型的字段进行模糊查询数据，hasWhere只有第一次生效

```
Goods::where($where)
            ->hasWhere()
            ->hasWhere()
```

**Comment by augushong** [comment]
hasWhere只能调用一次。

一个关联的查询，用hasWhere的数组条件或者闭包条件。


多个表的关联查询，直接用withJoin，然后用where表前缀查询。

where('a.status',0)->where('b.status',1)

**Comment by ajiho** [comment]
> hasWhere只能调用一次。
> 
> 一个关联的查询，用hasWhere的数组条件或者闭包条件。
> 
> 多个表的关联查询，直接用withJoin，然后用where表前缀查询。
> 
> where('a.status',0)->where('b.status',1)

感谢。
