### ISSUE TITLE
[bug] query原生参数绑定，值始终为string

### ISSUE THREAD

**Issue by choin1314** [top-think/think-orm#380]
`$ceshi  = 11;
		$ceshi1 = 22;
		Db::query("update xxx set content = json_replace(`content`, '$.day', JSON_ARRAY(:ceshi, :ceshi1)) where name = 'xxx'", [
			'ceshi' => $ceshi,
			'ceshi1' => $ceshi1
		]);`

为题所在：
PDOConnection.php（bindValue方法中）$result = $this->PDOStatement->bindValue($param, $val);
使用了默认PDO::PARAM_STR  没有进行值的检测

--------------------------

比较纳闷的是bindValue方法中有个is_array检测，
`Db::query('sql....', [
'param_1' => [111,111]
'param_2' => [222,222]
]);`
再次运行上方的sql，发现参数绑定值为int了...........
这么是何用？ 官方给个答复呀

**Comment by liu21st** [comment]
数组方式的时候 第一个值是数据 第二个值表示字段绑定类型

**Comment by choin1314** [comment]
> 数组方式的时候 第一个值是数据 第二个值表示字段绑定类型

我可能没表达清楚，我的意思是， 原本传入的值是int型，这里会默认转到了string，使用json_replace会造成类型不匹配，所以不应该是传入啥类型是什么类型么？    望答疑解惑

**Comment by liu21st** [comment]
原生查询 是不知道字段是什么类型的 必须指定参数绑定的类型
