### ISSUE TITLE
不支持纯数字的数据库字段

### ISSUE THREAD

**Issue by ccpwcn** [top-think/think-orm#384]
使用查询构造器Db.table($tableName)->insert和insertAll时，如果数据库中有纯数字的字段（比如2022），此时insert或insertAll的参数data的key也存在该字段，例如这样的数据：
```
[
    '2022' => 1,
    'name' => 'my name'
]
```
在入库时，文件vendor/topthink/think-orm/src/db/Builder.php的第158行这里的逻辑会出现错误。

逻辑分析：
如果数组的key是个数字，在vendor/topthink/think-orm/src/db/Builder.php的第149行，调用`$item = $this->parseKey($query, $key, true)`将该key转为字符串形式的$item，但是紧接着并没有使用这个$item变量，而是在158行调用strpos时传入了$key（这是数字类型），所以会抛出异常，导致数据入库失败

**Comment by augushong** [comment]
就是不支持的，在gitee就说了。
