### ISSUE TITLE
v2.0.55  语法错误: unexpected '(' ..../model/relation/MorphTo.php:148

### ISSUE THREAD

**Issue by xhwsd** [top-think/think-orm#385]
v2.0.55  语法错误: unexpected '(' ..../model/relation/MorphTo.php:148

**Comment by xhwsd** [comment]
https://www.php.net/manual/zh/language.oop5.basic.php
(PHP 8.0.0 起，支持任意表达式中使用 new。如果表达式生成一个 string，这将允许更复杂的实例化。表达式必须使用括号括起来。)

**Comment by nanziok** [comment]
PHP 8.0.0 起，支持任意表达式中使用 new。不得不说，这是一个糟糕的实现。为了保持向下兼容，请勿使用。@yunwuxin
``` 
// $className = new ($this->parseModel($type)); 改为
$className = $this->parseModel($type);
/** @var Model $model */
$model = new $className;
```

**Comment by xhwsd** [comment]
顺便把 [166行](https://github.com/top-think/think-orm/blob/e1974a4c3b1b4c5b808fcc0863fc254e711dee13/src/model/relation/MorphTo.php#L166) 注释修正下
