### ISSUE TITLE
2.0.57 $model->getChangedData() 无法获取数据

### ISSUE THREAD

**Issue by xhwsd** [top-think/think-orm#416]
v2.0.57 在执行` $模式->一对多关联()->saveAll($data)`后，在关联模型写入前事件下执行`$model->getChangedData()`返回空数据。
项目依赖 `$model->getChangedData()` 来判断改变字段，然后执行对应动作！

> 哎，要我小命~

**Comment by axguowen** [comment]
这个v2.0.57出了好多问题，不要更新
