### ISSUE TITLE
模型关联与载入，不能一同缓存吗？

### ISSUE THREAD

**Issue by augushong** [top-think/think-orm#418]
```
$list_region = AppRegion::with(['appRegionList'])->where('level', 1)->cache(true)->select();
```

像这样一个语句，只有第一个查询缓存了，with的查询并没有缓存。
这样的应该一同缓存吧，怎么给缓存呢？

**Comment by liu21st** [comment]
关联数据缓存有一个专门的withCache方法

**Comment by lascyb** [comment]
> 关联数据缓存有一个专门的withCache方法

使用 withCache 时发现，新增记录后关联的数据缓存不刷新，不知道key是根据什么逻辑生成的，尝试通过设置withCache的tag参数，然后通过tag手动删除缓存也是无效的
