### ISSUE TITLE
->where多维数组错误

### ISSUE THREAD

**Issue by choin1314** [top-think/think-orm#422]
->where()
使用多维数组时，如果 数组索引不是从0开始 会导致错误，
6.1.2 topthink\think-orm\src\db\Builder.php ，380行

目前我看了下是399行，替换了函数
} elseif (str_contains($field, '|')) {

----------------------------

比如where：
$where = [
  ['qq', '=', '1111'],
  ['qq', '=', '1111']
];
unset($where[0])

**Comment by liu21st** [comment]
不清楚你具体是什么错误 示例代码是什么

**Comment by choin1314** [comment]
> 不清楚你具体是什么错误 示例代码是什么
$where = [
['qq', '=', '1111'],
['qq', '=', '1111'],
['qq', '=', '1111']
];
unset($where[0])
->where($where)   报错，索引0没有了，
$where索引是 0,1,2,3,4,......正常
如果不顺序了就出错了

**Comment by liu21st** [comment]
为啥会有这样的代码？
你既然是传入的条件 肯定是处理后 统一传入where方法

**Comment by liu21st** [comment]
改进过了
