### ISSUE TITLE
使用mongo 模型的调用db方法  提示lazyFields 不存在

### ISSUE THREAD

**Issue by xw43230855** [top-think/think-orm#437]

**Comment by liu21st** [comment]
具体代码？

**Comment by xw43230855** [comment]
$data =    (new Mongo_model())->where("c2_code","AA")->find();

method not exist:think\db\Mongo->lazyFields|#0 /var/www/jmd_front/common/opp/vendor/topthink/think-orm/src/Model.php(393): think\db\BaseQuery->__call('lazyFields', Array)

**Comment by liu21st** [comment]
修正了

**Comment by Hhh0121** [comment]
> 修正了

@liu21st 是在哪个版本修正的，我用的3.0.8还是这样
