### ISSUE TITLE
tp6 往mongo插入null的时候会转为字符串

### ISSUE THREAD

**Issue by yinbug** [top-think/think-orm#438]
为什么tp6 往mongo插入null的时候会转为字符串啊。怎么说类型也不应该改变呀。

![IWQR23)VNK3~DQ6NB@P1%@S](https://user-images.githubusercontent.com/37343304/229464447-256a2be0-0e8d-4721-aa58-37b0aafc4711.png)

**Comment by yinbug** [comment]
@liu21st  有人能瞧一瞧吗?

**Comment by liu21st** [comment]
> @liu21st 有人能瞧一瞧吗?

提交PR就行了

**Comment by yinbug** [comment]
提交的pr被取消了
