### ISSUE TITLE
model->saveAll() bug

### ISSUE THREAD

**Issue by back0893** [top-think/think-orm#44]
model 下的340后 对比tp5.1的model
/**
    * 新增数据是否使用Replace
    * @access public
    * @param  bool $replace
    * @return $this
    */
    public function replace($replace = true)
    {
        $this->replace = $replace;
        return $this;
    }

缺少replace方法,导致saveAll 出错

**Comment by back0893** [comment]
emm,貌似composer上的没有更新到最新版本...

**Comment by liu21st** [comment]
感谢反馈 已经修正
