### ISSUE TITLE
withoutGlobalScope关闭全局范围查询 依然会执行$globalScope定义的查询范围

### ISSUE THREAD

**Issue by poetryiii** [top-think/think-orm#443]
![image](https://user-images.githubusercontent.com/30397859/231051692-3b6f936f-50a3-400a-a9ac-4f812fd616cf.png)
![image](https://user-images.githubusercontent.com/30397859/231051708-e6dde3b9-9ea1-4633-9144-bd184bd855a2.png)

**Comment by liu21st** [comment]
你这个代码又没有关闭任何全局查询范围

**Comment by poetryiii** [comment]
> 你这个代号又没有关闭任何全局查询范围

官方文档 https://www.kancloud.cn/manual/thinkphp6_0/1037586 写的是：
如果需要动态关闭所有的全局查询范围，可以使用：
```
User::withoutGlobalScope()->select();
```

**Comment by poetryiii** [comment]
> 你这个代号又没有关闭任何全局查询范围

我提交了一个pr，麻烦看下有没有问题
https://github.com/top-think/think-orm/pull/444

**Comment by liu21st** [comment]
我测试并没有发现问题 你输出的值并不是在实际查询的时候调用的，而是由于getFieldType方法调用的时候 在__call里面调用的

**Comment by poetryiii** [comment]
> 我测试并没有发现问题 你输出的值并不是在实际查询的时候调用的，而是由于getFieldType方法调用的时候 在__call里面调用的

好吧，这个问题确实是讲错了，但按照官方文档的写法
如果需要动态关闭所有的全局查询范围，可以使用：User::withoutGlobalScope()->select();
但是这个$globalScope是无法重置的，依然会执行$globalScope内定义的查询范围

**Comment by liu21st** [comment]
对于你的某次查询来说 是生效的，而且很容易验证

**Comment by poetryiii** [comment]
> 对于你的某次查询来说 是生效的，而且很容易验证

不太明白为什么只能生效一次，withoutGlobalScope传进的是null，不走scope方法，但是为什么不能全部生效呢，不好意思，这块不太理解

**Comment by poetryiii** [comment]
> > 对于你的某次查询来说 是生效的，而且很容易验证
> 
> 不太明白为什么只能生效一次，withoutGlobalScope传进的是null，不走scope方法，但是为什么不能全部生效呢，不好意思，这块不太理解

上面说的不是代码不理解，我只是不太明白为什么这么写
如果这么实现会不会有问题https://github.com/top-think/think-orm/pull/444

**Comment by poetryiii** [comment]
> > > 对于你的某次查询来说 是生效的，而且很容易验证
> > 
> > 
> > 不太明白为什么只能生效一次，withoutGlobalScope传进的是null，不走scope方法，但是为什么不能全部生效呢，不好意思，这块不太理解
> 
> 上面说的不是代码不理解，我只是不太明白为什么这么写 如果这么实现会不会有问题#444

不好意思，我明白了
