### ISSUE TITLE
v3 withJoin中使用field方法不符合预期

### ISSUE THREAD

**Issue by kyour-cn** [top-think/think-orm#469]
示例：
```php

        $list = ProjectEmployeeModel::where($where)
            ->withJoin([
                'projects' => function (Query $query) {
                    $query->field('title');
                }
            ])
            ->paginate($pageSize);
```

如上，返回结果中projects对象并不只查了title字段，而是所有

但是把title返回到了列表中与projects同级

是bug还是故意这样设计？如何使projects只查询指定字段呢？

**Comment by Hhh0121** [comment]
withJoin只能这样查询指定字段

**Comment by Hhh0121** [comment]
![image](https://github.com/top-think/think-orm/assets/127706674/61295e71-0575-41e3-a16d-8e09d7adcc56)
withJoin只能这样查询指定字段

**Comment by kyour-cn** [comment]
> ![image](https://private-user-images.githubusercontent.com/127706674/317997291-61295e71-0575-41e3-a16d-8e09d7adcc56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MDE5MTksIm5iZiI6MTcxMTcwMTYxOSwicGF0aCI6Ii8xMjc3MDY2NzQvMzE3OTk3MjkxLTYxMjk1ZTcxLTA1NzUtNDFlMy1hMTZkLThlMDlkN2FkY2M1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOVQwODQwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTM0YjkxYWQxZDc3MWFiZDk2ZTk1MDBmYzY4M2RiMTRiYzA4NmI0Yjg5OWVkZGEyZDAzYjZkNTQ5ZTUyMTRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qqwaXXTYat6tB-hbs4d0xdN804ZJKsLMikYhb4dErQY) withJoin只能这样查询指定字段

感谢，我已经知道了，忘了关闭

**Comment by MscZhao** [comment]
源码里面明明可以通过 field来获取限制字段的值 ，通过闭包指定field不生效? 麻烦解答一下，谢谢！
![image](https://github.com/user-attachments/assets/7eeb83b5-8dcc-4baa-9d2f-bace218154d9)
