### ISSUE TITLE
installAll 占用大量cpu

### ISSUE THREAD

**Issue by ZhangTianyi-1998** [top-think/think-orm#474]
![image](https://github.com/top-think/think-orm/assets/37682379/88be7440-620d-4722-80c3-f88451a4d751)

![image](https://github.com/top-think/think-orm/assets/37682379/dd3084c0-8b9c-4214-962c-85f202c73fd5)

![7514a7b1818dc952468411ce2dd07fc4](https://github.com/top-think/think-orm/assets/37682379/9d756424-8e16-4d2a-99a9-9f33edddc429)

**Comment by liu21st** [comment]
新版解决过这个问题的 主要是因为参数绑定的原因
