### ISSUE TITLE
自动时间戳 错误

### ISSUE THREAD

**Issue by TTSimple** [top-think/think-orm#50]
`Uncaught Error: Class 'think\model\concern\DateTime' not found in /vendor/topthink/think-orm/src/model/concern/TimeStamp.php:49`

建议修改为

`        
if ($timestamp) {
            $dateTime = new \DateTime();
            $dateTime->setTimestamp($time);
        } else {
            $dateTime = new \DateTime($time);
        }
`

**Comment by liu21st** [comment]
已经修正
