### ISSUE TITLE
whereRaw绑定，bug

### ISSUE THREAD

**Issue by choin1314** [top-think/think-orm#502]
tp:8.0.3

![image](https://github.com/top-think/think-orm/assets/73475361/308adab9-3f90-4f07-b34a-026ef694efe0)

结果：
![image](https://github.com/top-think/think-orm/assets/73475361/5ec2e516-42bb-46b8-99b6-204fdcd0ab90)
这什么鬼？  为啥要自动加了 '' ？ 
在tp6上没有这个问题

**Comment by liu21st** [comment]
参数绑定不需要加引号 自动识别参数类型的
