### ISSUE TITLE
一对一关联hasWhere和where同时使用bug

### ISSUE THREAD

**Issue by choin1314** [top-think/think-orm#512]
![1a9bfdc2deb217d82e74ce3201274a7a7af52820 webp](https://github.com/top-think/think-orm/assets/73475361/d5d9b827-1c6c-485d-9213-f77e25ca6586)

如图，where没有自动设置别名

**Comment by TTC1002335644** [comment]
兄弟，我也遇到了这个问题了，不知为何还是没有修复。

**Comment by choin1314** [comment]
不光是这里， order里也不自动设置别名，醉了……

**Comment by TTC1002335644** [comment]
> 不光是这里， order里也不自动设置别名，醉了……

还是不要用hasWhere了。

**Comment by choin1314** [comment]
> > 不光是这里， order里也不自动设置别名，醉了……
> 
> 还是不要用hasWhere了。

秒回啊兄弟……

**Comment by choin1314** [comment]
> > 不光是这里， order里也不自动设置别名，醉了……
> 
> 还是不要用hasWhere了。

不用hasWhere你咋关联查询啊，我写了个中间件，自动去匹配search字段了
