### ISSUE TITLE
不开启字段缓存的情况下，即使模型中设置了schema属性，在新增数据的时候依然会从数据库中获取表字段信息

### ISSUE THREAD

**Issue by yuyue8** [top-think/think-orm#524]
![image](https://github.com/top-think/think-orm/assets/48197835/e1faf723-b690-4274-aa1b-d742138cf12f)
![image](https://github.com/top-think/think-orm/assets/48197835/dbae2a6f-ed98-45de-b8f2-1ed48a7b5109)
![image](https://github.com/top-think/think-orm/assets/48197835/b8e1dc55-f654-4df5-a6bf-68c4fdc5802d)

**Comment by liu21st** [comment]
开发版做了改进 可以测试下 模型设置 autoInc属性
