### ISSUE TITLE
inc, dec, setInc, setDec 步长应该支持整型、浮点型、字符串类型

### ISSUE THREAD

**Issue by jerry-wolf** [top-think/think-orm#545]
之前版本虽然在 PHPDoc 里面声明了 `$step` 为 `integer`，但是那毕竟对 PHP 来说只是个注释，倒是一直能使用。现在使用 type hint 以后，至少我在 PHP 8.2 下会报 `Implicit conversion from float-string \"29.90\" to int loses precision` 这样的错误，而增减一个非整数值又是一个常用的用例，所以希望支持非整数值，毕竟之前一直是这么用的。
之所以要支持字符串类型是因为 PHP 没有十进制类型，所以为了不丢失精度，SQL 中的十进制值会在 PHP 中被转换为字符串。

**Comment by liu21st** [comment]
目前已经支持浮点型了 至于字符串类型应该不需要 本身已经优化过对bigint的支持了的
