### ISSUE TITLE
Cache不支持tag

### ISSUE THREAD

**Issue by qq475281441** [top-think/think-orm#56]
cache函数不支持tag操作，但是cache函数的第三个参数却是tag，实际上代码实现被删了

**Comment by liu21st** [comment]
因为考虑到很多缓存类都没有实现tag接口

**Comment by qq475281441** [comment]
> 因为考虑到很多缓存类都没有实现tag接口

其实这个功能还是很方便的，我已自行加上，只是这样就不能用官方的composer了
`
protected function cacheData($key, $data, $config = [])
    {
	    if (isset($config['tag'])) {
		    $this->cache->tag($config['tag'])->set($key, $data, $config['expire']);
	    } else {
		    $this->cache->set($key, $data, $config['expire']);
	    }
    }
`
其实代码就一点点，加上去对于没有实现tag的缓存类也没有什么影响。
