### ISSUE TITLE
where和hasWhere同时使用会出现的bug

### ISSUE THREAD

**Issue by TTC1002335644** [top-think/think-orm#560]
出现一个很奇怪的现象，如果where和hasWhere同时使用的情况。在连贯操作中，如果先试用where(条件1)->hasWhere(.....)，这样的话，where条件1就不生效了。
但是使用 hasWhere(.....)->where(条件1) 时，条件1就生效了

**Comment by big-dream** [comment]
`hasWhere`是`Model`的，`where`是`Db`的。模型尽量先执行模型的方法，不然是会有些问题。写代码的时候先自己注意下吧

**Comment by TTC1002335644** [comment]
> `hasWhere`是`Model`的，`where`是`Db`的。模型优化模型，不然会有些问题。

所以这个算不算bug？这个实在有点难以接受。毕竟从大多数的认知中where和hasWhere应该是同级的。而且手册也没有为这一点做特别说明

**Comment by big-dream** [comment]
不确定是不是BUG，只是提出当下最简单有效的解决办法

**Comment by TTC1002335644** [comment]
> 不确定是不是BUG，只是提出当下最简单有效的解决办法

行吧，先用这方法解决。再看看能不能引起官方注意吧。一直都没有什么动静。

**Comment by choin1314** [comment]
文档里有说，要确保hasWhere在where前面

**Comment by big-dream** [comment]
嗯，确实有说，那问题先关闭
![image](https://github.com/top-think/think-orm/assets/9215157/c1f8e032-4028-46ce-b80e-768ff134f11c)
