### ISSUE TITLE
2.0版本  合并的 模型增加setCacheKey方法用于设置自动缓存key 这快代码有问题

### ISSUE THREAD

**Issue by songpengfei-lv** [top-think/think-orm#561]
<img width="898" alt="94c7f6dd9fc19dd5e2c2c982ebe97c0" src="https://github.com/top-think/think-orm/assets/52516481/3ae0e520-b7b7-4d9e-b3d6-71ce43e93eb1">

建议修改成
    public function setCacheKey($key)
    {
        $this->cacheKey = $key;
        return $this;
    }

**Comment by big-dream** [comment]
是不是php版本太低

**Comment by songpengfei-lv** [comment]
> 是不是php版本太低
PHP7.2的，希望2.0能兼容下老版本

**Comment by big-dream** [comment]
明天我测试下，正常来说php7.2应该是支持联合类型的。

**Comment by big-dream** [comment]
是有问题，在 https://github.com/top-think/think-orm/commit/f74f60e52aa0cd1a6a93c610194bcfd719128165 已修复，感谢您的反馈！
