### ISSUE TITLE
采用数组方式配置分布式的数据库参数的时候，报Array to string conversion错误

### ISSUE THREAD

**Issue by znau** [top-think/think-orm#578]
https://doc.thinkphp.cn/v8_0/distributed.html 根据文档，如果hostname等参数按数组方式配置
 ` 
  ...
  'hostname' =>[ '192.168.1.1','192.168.1.2','192.168.1.3'],  
  ...
`

那么 think-orm/src/db/PDOConnection.php 的 getSchemaCacheKey  方法 就会报错：Array to string conversion

`  $this->getConfig('hostname') . '_' . $this->getConfig('hostport') . '|' . $schema;  `

$this->getConfig('hostname')  获取的是数组

**Comment by liu21st** [comment]
已经修正
