### ISSUE TITLE
[BUG] 使用PGSQL 查询数据库时，使用函数 Find 返回数据始终为NULL

### ISSUE THREAD

**Issue by luotianyil** [top-think/think-orm#589]
使用PGSQL 查询数据库时，使用函数 Find 返回数据始终为NULL

查询代码如下：
Db::connect('pgsql')  -> table('table_name')  -> find();

当指定条件后查询结果返回正常
Db::connect('pgsql')  -> table('table_name') -> where([ 'id' => 1 ])  -> find();

**Comment by big-dream** [comment]
如果没有任何的查询条件 并且也没有调用order方法的话 ，find查询不会返回任何结果。
