### ISSUE TITLE
我如何遍历模型的所有数据包括with的数据

### ISSUE THREAD

**Issue by netmou** [top-think/think-orm#605]
我想在model的基类用onAfterRead 事件去处理所有查询到的id，主表的id可以通过getData获得，但是 $row  = EmailReceiver::with('sender') ->where($where)  ->find();   像这样的width查询我就无法遍历了，因为在基类无法得知子类有个sender数据，我应当怎么做呢，我看到model\concern\Attribute 有一个私有变量$get存放着获取器数据，但是外边无法直接使用这个变量，能否增加方法获取$get的值呢

**Comment by big-dream** [comment]
可以通过 `$row->sender` 去获取关联模型 `sender` 的数据。

**Comment by netmou** [comment]
在基类我不知道有sender这个东西啊

**Comment by netmou** [comment]
基类做的是通用的事情

**Comment by big-dream** [comment]
可以用 `getRelation()` 方法：
```php
$info = Orders::with(['user'])->where('id', 1)->find();
dump($info->getRelation()); // ['user' => ...]
```

**Comment by netmou** [comment]
```php

/**
 * 自定义模型基类
 */
class BaseModel extends Model
{

  // ....



    public  static  function onAfterRead($model){
        file_put_contents('111112223.txt',"\r\n----\r\n".var_export($model->getRelation(),true),FILE_APPEND);
        ;
        //exit;
    }
    
    
}
```
onAfterRead 获取不到数据

**Comment by big-dream** [comment]
应该是触发 onAfterRead 时，还未查询关联模型的数据
