### ISSUE TITLE
[特性] ORM考虑对`Enum` 的提供支持

### ISSUE THREAD

**Issue by NHZEX** [top-think/think-orm#607]
在`>=8.1`的环境下提供对`Enum`的支持，能对传入的`Enum::Xxx`执行`Enum::Xxx->value`获取有效值。

支持场景：查询条件、写入值、模型`type`能定义直接转换为`Enum`对象。

**Comment by liu21st** [comment]
这个是有计划的

**Comment by big-dream** [comment]
`3.1` 版本直接调整最低 php 版本为 `8.1`。
`php 8.0` 于 `2023-11-26` 结束安全支持，`php 8.1` 于 `2025-12-31` 结束安全支持。
[PHP 8.1 包括枚举、只读属性、First-class 可调用语法、纤程、交集类型和性能改进等。](https://www.php.net/releases/8.1/zh.php)

**Comment by liu21st** [comment]
已经添加简单支持
