### ISSUE TITLE
$data = EmailReceiver::with('sender')->field('read_time,title')->select(); 又出现n+1问题

### ISSUE THREAD

**Issue by netmou** [top-think/think-orm#615]
// 这样没问题
$data = EmailReceiver::with('sender')->select(); 
// 这样现n+1问题
$data = EmailReceiver::with('sender')->field('read_time,title')->select();

**Comment by office360** [comment]
demo
$data = Db::view('admin','*')
                ->view('user','username,mobile','user.id=admin.uid')
                ->view('auth_group_access','group_id','auth_group_access.uid=admin.id')
                ->view('auth_group','title','auth_group.id=auth_group_access.group_id')
                ->where('admin.uid','>',1)//有查询条件的时候就会报错
                ->order('admin.id desc')
                ->paginate(['list_rows' => $limit,'query' =>$param], false)->toArray();
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
/vendor/topthink/think-orm/src/db/concern/JoinAndViewQuery.php ，218行
if (isset($options['order'])) {
     return;
}
导致视图查询有where条件查询时 报错Undefined array key \"order\" 
改成
if (!isset($options['order'])) {
     return;
}
后查询正常
