### ISSUE TITLE
查询范围

### ISSUE THREAD

**Issue by php-liuxh** [top-think/think-orm#617]
File::queryTable('abc')->queryTableId(12)->queryTypeIn([1,2,3])->delete();
这样使用有问题吗？
会报错误：delete without condition
File::queryTable('abc')->queryTableId(12)->queryTypeIn([1,2,3])->find();
查询就不会报错
3.0.15版是可以正常删除

**Comment by liu21st** [comment]
请补充详细说明

**Comment by big-dream** [comment]
https://github.com/top-think/think-orm/commit/c18daf3d8089e0f393f2a9474966a04a95fc6118 可以更新到最新版本再试试。
