### ISSUE TITLE
withSearch搜索器，在查询条件字段值为0时，withSearch方法中直接过滤掉了条件，导致查询结果异常。

### ISSUE THREAD

**Issue by rockyhu** [top-think/think-orm#618]
withSearch搜索器，在查询条件字段status值为0时，withSearch方法中直接过滤掉了条件，导致查询结果异常。
<img width="1031" alt="image" src="https://github.com/user-attachments/assets/a132104f-e663-4e92-9d17-196e9a77b13f">
<img width="1100" alt="image" src="https://github.com/user-attachments/assets/cf3f12a3-49c5-4cf5-9666-3e5d73a5cb2c">

`    /**
     * 使用搜索器条件搜索字段.
     *
     * @param string|array $fields 搜索字段
     * @param mixed        $data   搜索数据
     * @param bool         $strict 是否严格检查数据
     *
     * @return $this
     */
    public function withSearch($fields, $data = [], bool $strict = true)
    {
        if (is_string($fields)) {
            $fields = explode(',', $fields);
        }

        $likeFields = $this->getConfig('match_like_fields') ?: [];

        foreach ($fields as $key => $field) {
            if ($field instanceof Closure) {
                $field($this, $data[$key] ?? null, $data);
            } elseif ($this->model) {
                // 检查字段是否有数据
                if ($strict && (!isset($data[$field]) || empty($data[$field]))) {
                    continue;
                }

                $fieldName = is_numeric($key) ? $field : $key;
                $method    = 'search' . Str::studly($fieldName) . 'Attr';
                if (method_exists($this->model, $method)) {
                    $this->model->$method($this, $data[$field], $data);
                } elseif (isset($data[$field])) {
                    $this->where($fieldName, in_array($fieldName, $likeFields) ? 'like' : '=', in_array($fieldName, $likeFields) ? '%' . $data[$field] . '%' : $data[$field]);
                }
            }
        }

        return $this;
    }`

以上代码在if ($strict && (!isset($data[$field]) || empty($data[$field]))) 判断是满足empty($data[$field])条件($data['status']=0)，导致直接continue了。这应该是一个Bug，期望能够修复。

**Comment by FlameMida** [comment]
离谱,参数类型都变了居然没写breaking

**Comment by liu21st** [comment]
withsearch方法的第三个参数传入false试下

**Comment by rockyhu** [comment]
> withsearch方法的第三个参数传入false试下

通过这个可以临时解决问题，这个问题在开发环境最新的版本下存在的。我线上版本要低一些，不存在这个问题。

**Comment by rockyhu** [comment]
> 离谱,参数类型都变了居然没写breaking

没看明白，您指的哪个参数类型变了？

**Comment by liu21st** [comment]
搜索器功能有调整 当表单没有数据或者为空的时候默认不会执行 所以当数据为0的时候没有执行 这个后面可以优化改进下

**Comment by rockyhu** [comment]
> 搜索器功能有调整 当表单没有数据或者为空的时候默认不会执行 所以当数据为0的时候没有执行 这个后面可以优化改进下

点赞

**Comment by FlameMida** [comment]
> > 离谱,参数类型都变了居然没写breaking
> 
> 没看明白，您指的哪个参数类型变了？

public function withSearch($fields, $data = [], string $prefix = '') 旧版本的签名是这样的，第三个参数变了

**Comment by rockyhu** [comment]
> > > 离谱,参数类型都变了居然没写breaking
> > 
> > 
> > 没看明白，您指的哪个参数类型变了？
> 
> public function withSearch($fields, $data = [], string $prefix = '') 旧版本的签名是这样的，第三个参数变了

明白了。

**Comment by liu21st** [comment]
> > > 离谱,参数类型都变了居然没写breaking
> > 
> > 
> > 没看明白，您指的哪个参数类型变了？
> 
> public function withSearch($fields, $data = [], string $prefix = '') 旧版本的签名是这样的，第三个参数变了

prefix参数基本上没有什么用 手册也没有提及
