### ISSUE TITLE
Non-static method think\Model::withAttr() cannot be called statically

### ISSUE THREAD

**Issue by ken678** [top-think/think-orm#619]
文档写了withAttr在select调用，就报标题那个错误
![image](https://github.com/user-attachments/assets/7984f048-5475-48c2-ba4f-413ca2c626bf)

使用下面放select之后，就正常
![image](https://github.com/user-attachments/assets/afd2d710-d4e5-46d5-8b82-fda4a49cbaa7)

**Comment by liu21st** [comment]
其实不要在第一个位置调用即可 我更换了一个方法名 避免model类里面的同名方法冲突
