### ISSUE TITLE
最新2.0.1的bug

### ISSUE THREAD

**Issue by back0893** [top-think/think-orm#62]
在chace里面依赖的think\App了类,但是compoer并没有包含.
2.0.0正常使用

**Comment by liu21st** [comment]
是什么用法出错了？

**Comment by augushong** [comment]
我也遇到这个问题.按照手册,直接composer使用,会报App类不存在的问题,这行代码来自think-cache.

**Comment by liu21st** [comment]
最新版本我测试没有发现问题
