### ISSUE TITLE
模型查询结果JSON输出异常：Malformed UTF-8 characters, possibly incorrectly encoded

### ISSUE THREAD

**Issue by yinxu46** [top-think/think-orm#621]
模型查询结果JSON输出异常：Malformed UTF-8 characters, possibly incorrectly encoded

数据库存储为：string(12) "微信联系"
模型查询结果：string(12) "微****��系"

- 通过 Order::find(id) 查询结果返回正常： string(12) "微信联系"

- 通过  $order = Order::alias('o')
            ->leftJoin('order_employee oe', 'oe.order_id = o.id')
            ->field('o.*, ...')
            ->where($condition)
            ->find();

查询结果返回异常：string(12) "微****��系"

**Comment by liu21st** [comment]
看下你生成的sql语句有没有问题 用sql语句直接去数据库执行下结果比较下

**Comment by yinxu46** [comment]
搞错了，attr 处理的时候出的问题。

**Comment by big-dream** [comment]
> 搞错了，attr 处理的时候出的问题。

是更新后才出现的嘛，还是没更新就这样
