### ISSUE TITLE
视图带分页paginate查询单有查询条件时报错 Undefined array key "order"

### ISSUE THREAD

**Issue by office360** [top-think/think-orm#623]
$data = Db::view('admin','*')
->view('user','username,mobile','user.id=admin.uid')
->view('auth_group_access','group_id','auth_group_access.uid=admin.id')
->view('auth_group','title','auth_group.id=auth_group_access.group_id')
->where('admin.uid','>',1)//有查询条件的时候就会报错
->order('admin.id desc')
->paginate(['list_rows' => $limit,'query' =>$param], false)->toArray();
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

/vendor/topthink/think-orm/src/db/concern/JoinAndViewQuery.php ，218行
if (isset($options['order'])) {
return;
}
导致视图查询有where条件查询时 报错Undefined array key "order"
改成
if (!isset($options['order'])) {
return;
}
后查询正常

**Comment by liu21st** [comment]
你这个是什么版本的 应该已经修正过的
