### ISSUE TITLE
3.0.25 模型使用value方法获取字段值有问题

### ISSUE THREAD

**Issue by jesuer** [top-think/think-orm#625]
3.0.25 模型使用value获取字段值时，如果字段是json，不会自动转为数组

比如：`User::where('id',1)->value('likes');`

返回：`"['踢球','旅游']"`

3.0.25 之前的版本

返回：`['踢球','旅游']`

![image](https://github.com/user-attachments/assets/449db9be-4aa7-42e8-9702-b1b7d84b8b44)

源码中这里没有处理，修改为如下：

![image](https://github.com/user-attachments/assets/f85689d7-0296-4c04-9013-eb1af9831f0a)

**Comment by liu21st** [comment]
已经修正 感谢反馈
