### ISSUE TITLE
json_contains

### ISSUE THREAD

**Issue by flowerwOw0316** [top-think/think-orm#627]
这个函数频率使用还挺高的，请问像laravel的whereJsonContains和orWhereJsonContains这样的方法有吗？

**Comment by big-dream** [comment]
目前暂时没有，可以先使用 `->whereRaw('JSON_CONTAINS(extra, 1, "$.a")')`

**Comment by liu21st** [comment]
JSON_CONTAINS并好用 还不如直接用 where('json->name','think')呢

**Comment by flowerwOw0316** [comment]
没有,我有一个字段存区域信息是这样存的[["11", "110102"], ["11", "110105"], ["11", "110106"], ["11", "110107"]],这样前端只需要传一些匹配的值给我使用JSON_CONTAINS就特别方便

**Comment by big-dream** [comment]
可以试试最新开发版的 `->whereJsonContains()` 和 `->whereOrJsonContains()` 方法

https://github.com/top-think/think-orm/blob/399200e3540660ffcef5482f066c1786bd935579/src/db/concern/WhereQuery.php#L276-L301
