### ISSUE TITLE
syncWithPivotValues有这个方法吗

### ISSUE THREAD

**Issue by flowerwOw0316** [top-think/think-orm#633]
比如我想同步中间表的时候，顺便带个条件，$user->roles()->syncWithPivotValues([1, 2, 3], ['active' => true]);

**Comment by big-dream** [comment]
可以用where方法设置条件

**Comment by flowerwOw0316** [comment]
说错了，是同步中间表的时候，将中间表的某个字段值设置固定的值，比如active为true

**Comment by big-dream** [comment]
可以查询出来再更新，应该也能满足你的需求

**Comment by liu21st** [comment]
有sync方法的

**Comment by flowerwOw0316** [comment]
看源码看到了。。但是好难顶，我得将数据处理为【id作为键=>改中间表的字段作为值去用】,而且有bug,比如我第一条记录在数据库中间表里面存有id为1的记录,当我第二次提交也有id为1的并不会将之前的清掉，而是会叠加。
举个例子
第一次提交是id为1的记录在中间表存着
第二次我提交了id为1,2,3的数组 
最后呈现出来的结果就是1,1,2,3的4条记录在数据库中，我也不知道描述清楚没

**Comment by liu21st** [comment]
第二个参数传入true就是现解除关联 然后再追加

**Comment by flowerwOw0316** [comment]
好的大佬，我再去看看
