### ISSUE TITLE
大佬呀 现在 field(['mdate']) 这种也不行呀

### ISSUE THREAD

**Issue by vsenver** [top-think/think-orm#64]

**Comment by vsenver** [comment]
![image](https://user-images.githubusercontent.com/37345090/58692450-330e1b00-83c1-11e9-913a-6fbb33e6c06a.png)

**Comment by vsenver** [comment]
![image](https://user-images.githubusercontent.com/37345090/58694115-d3197380-83c4-11e9-8f08-8166332ba038.png)

**Comment by liu21st** [comment]
已经修正
