### ISSUE TITLE
连接Oracle数据库charset参数设置无效

### ISSUE THREAD

**Issue by TuringTrail** [top-think/think-orm#641]
![image](https://github.com/user-attachments/assets/256edabb-ed71-4dab-ac3e-c24ba46f7e41)
database配置里面已经设置charset utf8编码，使用模型查询数据库但是设置不生效
但是使用oci_connect连接并设置编码则生效，无问题
![image](https://github.com/user-attachments/assets/3c9528ca-5bac-4d01-b419-ab1e4fd65b7d)

**Comment by big-dream** [comment]
试试 `PDO` 看看有没有这个问题

**Comment by TuringTrail** [comment]
> PDO

使用PHP原生PDO连接也是这样;编码设置无效

**Comment by big-dream** [comment]
> > PDO
> 
> 使用PHP原生PDO连接也是这样;编码设置无效

建议找找其它解决办法，这应该算是底层，框架层面不好处理。

**Comment by TuringTrail** [comment]
> > > PDO
> > 
> > 
> > 使用PHP原生PDO连接也是这样;编码设置无效
> 
> 建议找找其它解决办法，这应该算是底层，框架层面不好处理。

已解决问题;PHP环境缺少NLS_LANG环境变量,但是这应该也是底层BUG，我再连接时设置的charset没有生效,而且我发现只有Oracle有这个问题，目前可以使用环境变量配置NLS_LANG=.AL32UTF8解决
