### ISSUE TITLE
think-orm V2的发版频率是怎样的？还是去年的版本，提交到V2上的版本，ThinkPHP6中也用不了

### ISSUE THREAD

**Issue by phpdog** [top-think/think-orm#643]
think-orm V2的发版频率是怎样的？还是去年的版本，提交到V2上的版本，ThinkPHP6中也用不了。

ThinkPHP6 添加支持MySQL不等于操作表达式
https://github.com/top-think/think-orm/pull/640

这个分支合并了，但没发布V2的版本，还是用不了，请发一个最新版的V2的release.
https://github.com/top-think/think-orm/releases?q=v2&expanded=true

**Comment by liu21st** [comment]
建议尽量使用v3版本 后续应该不会增加功能了v2版本
