### ISSUE TITLE
\think\db\Where的offsetGet方法在运行时报错

### ISSUE THREAD

**Issue by LifeTimeNine** [top-think/think-orm#653]
PHP8.3
orm:3.0.28
方法: \think\db\Where:offsetGet
报错信息：During inheritance of ArrayAccess: Uncaught think\exception\ErrorException: Return type of think\db\Where::offsetGet(mixed $name) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
给方法加上返回类型【mixed】之后解决

**Comment by big-dream** [comment]
感谢反馈，目前流年老大已修正。
close of https://github.com/top-think/think-orm/commit/51f0c35f76c1d178e37d8e11e13ec3cb28790ebc
