### ISSUE TITLE
when 回调的第二个参数了？

### ISSUE THREAD

**Issue by xhwsd** [top-think/think-orm#655]
when 回调的第二个参数了？

<img width="333" alt="7A6920C4-70A7-4618-8F3A-ED6C4D5C61F7" src="https://github.com/user-attachments/assets/a3f5a21d-1b19-4775-b157-30fccc70f244">

<img width="848" alt="2C850374-1303-424b-B2D1-29F07BF24669" src="https://github.com/user-attachments/assets/dbd17f22-16b5-4146-923c-f0cea11dc93b">

**Comment by liu21st** [comment]
有什么问题么？查询条件的执行并不需要判断条件参数的

**Comment by xhwsd** [comment]
1. 6.x 支持，新版本不支持了（8.x 无缝升级？）
2. 回调带条件参数非常人性化和便捷

支持时：
```
$xx->when(request()->param('merchant_id/d'), function(Query $query, $merchantId) {
  // ...
})
```

不支持时：
```
$merchantId = request()->param('merchant_id/d')
$xx->when($merchantId, function(Query $query) use($merchantId) {
  // ...
})
```

**Comment by xhwsd** [comment]
这么好的功能，不知道为什么砍了，laravel也支持的~

### **ThinkPHP - 出色性能和优雅易用**

**Comment by liu21st** [comment]
我倒是觉得第二种方式 更灵活 而且大部分场景都不需要传参

**Comment by xhwsd** [comment]
大哥，别这样，咱们优雅点，在做搜索接口，如果 when 回调不带条件值，那得多很多行代码的！

**Comment by xhwsd** [comment]
随意挑个搜索接口给你看看，如果 when 回调不带条件值，想想真是噩梦啊！

<img width="922" alt="FE9BB907-FDE1-41b7-9E63-D87420605C87" src="https://github.com/user-attachments/assets/49d5ff83-6fae-4e92-9a96-98d7196920f2">

**Comment by big-dream** [comment]
麻了，这么写代码的嘛，看着就像多层 `if`
