### ISSUE TITLE
where数组查询，alias失效

### ISSUE THREAD

**Issue by Ibazhe** [top-think/think-orm#657]
> 这样更新之后的变化就是where条件变成括号里的了，但是如果在where之前有alias的话，这个括号里面的表名不会自动更改 

 _Originally posted by @Ibazhe in [4556263](https://github.com/top-think/think-orm/commit/4556263e1d7884e33a57099a41a6615a417053c9#commitcomment-150653845)_

**Comment by Ibazhe** [comment]
`\app\admin\model\Admin::query()->alias(['ba_admin' => 'admin'])->where([["ba_admin.id", "=", "1"]])->select();//报错
\app\admin\model\Admin::query()->alias(['ba_admin' => 'admin'])->where("ba_admin.id", "=", "1")->select();//正常`

**Comment by liu21st** [comment]
第二种才是建议用法 复杂查询推荐闭包 数组查询的话 尽量保持简单

**Comment by Ibazhe** [comment]
> 第二种才是建议用法 复杂查询推荐闭包 数组查询的话 尽量保持简单

一些基于tp的admin是会把大量的where参数组合成数组查询的

**Comment by liu21st** [comment]
$blog = Blog::alias('t')->where([['t.id','=',6]])->find(); 这种用法我测试没有问题哦

**Comment by Ibazhe** [comment]
> $blog = Blog::alias('t')->where([['t.id','=',6]])->find(); 这种用法我测试没有问题哦

如果把t.id的t换成原始表名呢

**Comment by liu21st** [comment]
> > $blog = Blog::alias('t')->where([['t.id','=',6]])->find(); 这种用法我测试没有问题哦
> 
> 如果把t.id的t换成原始表名呢

用原始表名 你定义alias方法干嘛？

**Comment by Ibazhe** [comment]
> > > $blog = Blog::alias('t')->where([['t.id','=',6]])->find(); 这种用法我测试没有问题哦
> 
> > 
> 
> > 如果把t.id的t换成原始表名呢
> 
> 
> 
> 用原始表名 你定义alias方法干嘛？

🥲行吧，更新之前还是可以的。更新之后就报错了。我看了代码，好像是Mysql类里面会自动把原始表名替换成定义的alias，但是更新后这种写法就不自动替换了

**Comment by liu21st** [comment]
你的alias方法用法就是错误的 怎么可能查询出来
