### ISSUE TITLE
[bug]在ThinkPHP模型关联查询中使用alias方法后，where条件中调用别名查询失败

### ISSUE THREAD

**Issue by q8018414** [top-think/think-orm#659]
#### 问题描述
在使用 ThinkPHP 模型查询时，模型支持使用数据库查询构造器进行查询，然而在升级到`"topthink/think-orm": "3.0.33"`后,在进行关联查询（如 `join` 关联或 `hasOne`/`belongsTo` 关联）时，使用了 `alias` 方法后，在 `where` 条件中使用`索引数组`调用别名查询会失败。

#### 复现步骤
1. 使用 `Model` 进行关联查询（如 `join` 或 `hasOne`/`belongsTo` 关联），当使用`alias`方法为模型或表设置别名后。
2. 在 `where` 条件中使用该别名进行查询。
3. 查询执行失败或无结果返回。

#### 预期结果
关联查询使用 `alias` 后，在 `where` 中能够正确使用`索引数组`调用别名进行查询。

#### 实际结果
在 `where` 条件中使用`索引数组`调用别名查询时，查询执行失败或无法返回正确结果。

#### 环境信息
- ThinkPHP 版本: 8.1.1
- think-orm 版本: 3.0.33
- PHP 版本: 8.0
- 数据库类型: 8.0

#### 代码示例
```php
// 示例代码，使用 alias 后查询
$user = UserModel::alias('u')
    ->join('profile p', 'u.id = p.user_id')
    ->where([['u.id','=',1],['u.status','=',1]])
    ->select();
```

**Comment by q8018414** [comment]
尚未测试DB类.但是怀疑DB类也出现了相同问题..

**Comment by liu21st** [comment]
什么错误？我测试没有问题 看下生成的sql语句是什么

**Comment by q8018414** [comment]
表述错误了.是在where中用原始表名不在会自动替换了.在之前的版本中.会自动替换为别名..不管是model类.还是DB类都会自动替换为别名..

 ```
Admin::query()->alias('a')->where([['admin.admin','=','123']])->select(); // 报错提示 : admin.admin 不存在
Admin::query()->alias('a')->where('admin.admin','=','123')->select();  //正常查询
Db::name('admin')->alias('a')->where([['admin.admin','=','123']])->select(); // 报错提示 : admin.admin 不存在
Db::name('admin')->alias('a')->where('admin.admin','=','123')->select(); //正常查询
```

**Comment by liu21st** [comment]
搞不懂为啥要这样用？既然用了别名 原始名自然就不能用了 手册里面也没提过能这样使用吧

**Comment by Ibazhe** [comment]
> 搞不懂为啥要这样用？既然用了别名 原始名自然就不能用了 手册里面也没提过能这样使用吧

原本就支持的，只不过在闭包内不支持了啊。我提交了pr，你看一下

**Comment by q8018414** [comment]
讲真..我也突然反应过来..有点反人类了.....真是前人挖坑..后人掉..麻了..

> 搞不懂为啥要这样用？既然用了别名 原始名自然就不能用了 手册里面也没提过能这样使用吧

**Comment by liu21st** [comment]
> > 搞不懂为啥要这样用？既然用了别名 原始名自然就不能用了 手册里面也没提过能这样使用吧
> 
> 原本就支持的，只不过在闭包内不支持了啊。我提交了pr，你看一下

不能因为原本就支持 就是正常的用法，规范用法才是关键 哪有为了错误的用法去修正的

**Comment by Ibazhe** [comment]
> > > 搞不懂为啥要这样用？既然用了别名 原始名自然就不能用了 手册里面也没提过能这样使用吧
> > 
> > 
> > 原本就支持的，只不过在闭包内不支持了啊。我提交了pr，你看一下
> 
> 不能因为原本就支持 就是正常的用法，规范用法才是关键 哪有为了错误的用法去修正的

算是防呆设计吧，哈哈哈

**Comment by q8018414** [comment]
#660 合并吗?其实..不管合并不合并..后面都要规范化修改这个逻辑..麻了..

**Comment by liu21st** [comment]
考虑到升级问题 还是合并了 不过下一个版本可能就不会兼容这种了 建议还是规范用法吧
