### ISSUE TITLE
现在版本的分页是不是有问题啊

### ISSUE THREAD

**Issue by EastHuang** [top-think/think-orm#66]
像Paginator.php里的getCurrentPage，声明返回的是int类型,但是在$_REQUEST里面拿到的是字符串，最后的return那里没处理就会导致报错，有些方法的访问控制好像也不太对，没办法一个个去看，麻烦你们查下吧

**Comment by EastHuang** [comment]
Connection.php里面的aggregate方法被设为protected,然后Query.php里面aggregate方法直接就去调用Connection.php里面的aggregate，又会导致报错

**Comment by liu21st** [comment]
think-orm 等最新框架稳定后 会再更新一个版本

**Comment by EastHuang** [comment]
可不可以再提一点，find()的参数为空的时候可不可以不要返回第一条数据，假如按文档里面删除的写法，
$user = User::find($id);$user->delete(); 如果提交的id为空，且代码没对$id是否未空做判断，这段代码早晚会把整张表删完，旧版本的get就不存在这个问题，这样写起来还不如以前的get

**Comment by liu21st** [comment]
@EastHuang 这个问题最新版本已经改进
