### ISSUE TITLE
2.0.7 和2.0.5版本不兼容

### ISSUE THREAD

**Issue by vsenver** [top-think/think-orm#67]
Uncaught InvalidArgumentException: Undefined db config:mysql   think-orm/src/DbManager.php:118
2.0.7 和2.0.5版本不兼容

**Comment by vsenver** [comment]
topthink/think-container/src/Container.php [line] 390
class not exists: \think\db\connector\Mongo

**Comment by vsenver** [comment]
mongodb 直接不兼容了

**Comment by liu21st** [comment]
因为新版的配置文件格式已经和框架统一了 除了mysql之外的驱动还需要重新测试，需要迟一点

**Comment by vsenver** [comment]
> 因为新版的配置文件格式已经和框架统一了除了mysql之外的驱动还需要重新测试，需要迟一点

噗噗噗  还好我phpstrom 有整个文件的历史记录

**Comment by liu21st** [comment]
你可以安装指定版本的，或者测试下最新提交的版本
