### ISSUE TITLE
PHP Notice:  Undefined variable: config in /www/wwwroot/tcp/vendor/topthink/think-orm/src/DbManager.php on line 186

### ISSUE THREAD

**Issue by sevend93** [top-think/think-orm#69]
PHP Notice:  Undefined variable: config in /www/wwwroot/tcp/vendor/topthink/think-orm/src/DbManager.php on line 186

$config 这个变量未定义哦，还是说应该是 $name

**Comment by liu21st** [comment]
修正过了的
