### ISSUE TITLE
模型不能执行更新操作

### ISSUE THREAD

**Issue by xushuhui1992** [top-think/think-orm#7]
我把think-orm放在yaf里面 ，模型不能正常使用更新，这两种方式都报错Fatal error: Uncaught think\Exception: where express error
1、$res = UserModel::update(['name' => 'wwang'],['uid'=>18]);

2、$user = new UserModel();
$user->allowField(true)->save(['name' => 'wwang'],['uid'=>18]);

报错源码是在Builder.php line 304 elseif (!($value instanceof \Closure)) { 这里

**Comment by liu21st** [comment]
这个问题我修正了下
