### ISSUE TITLE
建议移除Facade，使用think-container

### ISSUE THREAD

**Issue by techoner** [top-think/think-orm#77]
framework里也是

**Comment by liu21st** [comment]
think-container库独立后使用场景并不多，所以还是内置了的

**Comment by techoner** [comment]
写扩展包会用，一般都会包一个Facade，像laravel一样

**Comment by liu21st** [comment]
如果是开发基于TP的扩展 其实是可以直接用的 ，如果是开发独立的扩展 那么也可以用其它的容器库
