### ISSUE TITLE
Model.php在非composer加载器下会报错

### ISSUE THREAD

**Issue by tangzhangming** [top-think/think-orm#8]
codeigniter4框架，在composer下加载没问题，如果使用自带的加载器加载，遇到报错，Model.php文件中98行到112行，使用$config中auto_timestamp，datetime_format，resultset_type，query四个配置时未做判断，手动抛出警告Undefined index: auto_timestamp，不抛出则导致整个程序终止执行

**Comment by liu21st** [comment]
composer自动加载了src/config.php文件 你手动加载需要

**Comment by liu21st** [comment]
后者你在自己setConfig方法的时候传入完整的配置参数

**Comment by tangzhangming** [comment]
非常感谢，确实是这个问题，但是我建议判断一下，因为我是在继承Model的时候报错的，我想建一个模型基类，在基类构造函数中setConfig，但是如果您这里不判断的话，使用时只能在调用模型前setConfig

**Comment by liu21st** [comment]
强烈建议你通过composer安装使用，就算不用 也应该按照composer的加载规范 首先确保优先载入config.php文件
