### ISSUE TITLE
独立使用 withoutField 用不了.

### ISSUE THREAD

**Issue by duhawk** [top-think/think-orm#83]
Fatal error: Uncaught think\Exception: method not exist:V1\Model\Users->withoutField in...
....
/vendor/topthink/think-orm/src/db/Query.php on line 137....

**Comment by liu21st** [comment]
你安装的版本不对吧

**Comment by duhawk** [comment]
> 你安装的版本不对吧

我就是这样安装的 
composer require topthink/think-orm

**Comment by liu21st** [comment]
你这样安装不代表就是安装的最新版本 最新版本需要PHP7.1+ 所以如果你的php版本低 自动安装的是之前的老版本

**Comment by duhawk** [comment]
> 你这样安装不代表就是安装的最新版本 最新版本需要PHP7.1+ 所以如果你的php版本低 自动安装的是之前的老版本

我的php是7.3

**Comment by liu21st** [comment]
cli的版本不是你web的php版本

**Comment by liu21st** [comment]
你可以试下安装能不能成功 compser require topthink/think-orm:2.0.*

**Comment by duhawk** [comment]
> 你可以试下安装能不能成功 compser require topthink/think-orm:2.0.*

OK了,我升级了  "topthink/think-orm": "2.*.*"
withoutField 没问题了.
感谢.
建议,文档加一下升级什么的.

**Comment by liu21st** [comment]
这些都是composer的基础 估计是你之前安装的老版本 更新也是更新到老版本
