### ISSUE TITLE
$item = model::create();$item->id;获取不到新插入数据ID

### ISSUE THREAD

**Issue by MiloZheng** [top-think/think-orm#89]
BaseQuery::getLastInsID();这个方法获取到的数据为“0”；
根据这个方法追踪到PDOConnection::getLastInsID();这个方法最后返回的是$this->autoInsIDType($query,$inserId);返回之前最后的执行语句为insert语句。
当前可以获取到最后的插入ID。
PDOConnection::autoInsIDType();这个方法的第一句执行:$pk=$query->getAutoInc();这句执行完，最后执行语句为show full columns语句；
在这个位置最后插入的ID就被重置了。
请帮忙处理一下

**Comment by liu21st** [comment]
你可以用最新的开发版测试下再
