### ISSUE TITLE
Mongo `$this->trigger('', $master);` 其中$master未定义

### ISSUE THREAD

**Issue by hbh112233abc** [top-think/think-orm#90]
src/db/connector/Mongo.php 
`$this->trigger('', $master);` 其中$master未定义

**Comment by liu21st** [comment]
哪一行是未定义的？

**Comment by hbh112233abc** [comment]
> 哪一行是未定义的？

额 对不起 我这的版本是2.0.25的 所以其中249行提示$master未定义
