### ISSUE TITLE
Mysql字段是否为空判断有问题

### ISSUE THREAD

**Issue by iguoji** [top-think/think-orm#96]
\vendor\topthink\think-orm\src\db\connector\Mysql.php
getFields方法，第77行
原：`'notnull' => (bool) ('' === $val['null'])`
得到的结果永远是可以为空
改成：`'notnull' => (bool) ('NO' === $val['null'])`之后没问题

**Comment by taozhipeng1990** [comment]
官方没人了
在官网13年就有人反馈过这个问题。
20年了 还没修复

**Comment by taozhipeng1990** [comment]
刚看了一下master 还是没修复
............

**Comment by liu21st** [comment]
因为这个地方框架没有用到 所以也没有影响，已经修正。master分支是5.0版本 已经停止维护了
